// Word banks categorized by difficulty
const easyWords = [
  "the",
  "be",
  "to",
  "of",
  "and",
  "a",
  "in",
  "that",
  "have",
  "I",
  "it",
  "for",
  "not",
  "on",
  "with",
  "he",
  "as",
  "you",
  "do",
  "at",
  "this",
  "but",
  "his",
  "by",
  "from",
  "they",
  "we",
  "say",
  "her",
  "she",
  "or",
  "an",
  "will",
  "my",
  "one",
  "all",
  "would",
  "there",
  "their",
  "what",
  "so",
  "up",
  "out",
  "if",
  "about",
  "who",
  "get",
  "which",
  "go",
  "me",
  "when",
  "make",
  "can",
  "like",
  "time",
  "no",
  "just",
  "him",
  "know",
  "take",
  "people",
  "into",
  "year",
  "your",
  "good",
  "some",
  "could",
  "them",
  "see",
  "other",
  "than",
  "then",
  "now",
  "look",
  "only",
  "come",
  "its",
  "over",
  "think",
  "also",
  "back",
  "after",
  "use",
  "two",
  "how",
  "our",
  "work",
  "first",
  "well",
  "way",
  "even",
  "new",
  "want",
  "because",
  "any",
  "these",
  "give",
  "day",
  "most",
  "us",
];

const mediumWords = [
  "great",
  "another",
  "being",
  "between",
  "before",
  "through",
  "little",
  "still",
  "found",
  "should",
  "never",
  "world",
  "thought",
  "against",
  "going",
  "place",
  "where",
  "every",
  "under",
  "something",
  "right",
  "without",
  "different",
  "around",
  "system",
  "problem",
  "important",
  "however",
  "example",
  "during",
  "always",
  "children",
  "development",
  "government",
  "company",
  "business",
  "together",
  "program",
  "question",
  "research",
  "number",
  "country",
  "possible",
  "information",
  "community",
  "including",
  "education",
  "experience",
  "following",
  "available",
  "service",
  "national",
  "political",
  "building",
  "support",
  "economic",
  "technology",
  "management",
  "control",
  "process",
  "provide",
  "market",
  "individual",
  "specific",
  "performance",
  "project",
  "function",
  "general",
  "material",
  "standard",
  "practice",
  "computer",
  "network",
  "software",
  "security",
  "analysis",
  "application",
  "particular",
  "significant",
  "relationship",
];

const hardWords = [
  "acknowledge",
  "acquisition",
  "administration",
  "advertisement",
  "approximately",
  "architecture",
  "bureaucracy",
  "catastrophe",
  "characteristic",
  "chronological",
  "circumference",
  "collaboration",
  "comprehensive",
  "concentration",
  "consciousness",
  "consequently",
  "consideration",
  "contemporary",
  "controversial",
  "correspondence",
  "demonstration",
  "determination",
  "differentiate",
  "disappointment",
  "discrimination",
  "electromagnetic",
  "encyclopedia",
  "entrepreneurship",
  "environmental",
  "establishment",
  "experimentation",
  "extraordinary",
  "fundamentally",
  "generalization",
  "heterogeneous",
  "implementation",
  "inconvenience",
  "infrastructure",
  "initialization",
  "instantaneous",
  "interdependent",
  "interpretation",
  "investigation",
  "juxtaposition",
  "knowledgeable",
  "legitimately",
  "manufacturing",
  "mathematician",
  "mediterranean",
  "misconception",
  "nevertheless",
  "notwithstanding",
  "organizational",
  "overwhelmingly",
  "pharmaceutical",
  "philosophical",
  "predominantly",
  "professionalism",
  "pronunciation",
  "psychological",
  "questionnaire",
  "quintessential",
  "recommendation",
  "reconciliation",
  "rehabilitation",
  "representative",
  "responsibilities",
  "revolutionize",
  "simultaneously",
  "sophistication",
  "specification",
  "straightforward",
  "subconsciously",
  "subordinate",
  "substantially",
  "superintendent",
  "sustainability",
  "systematically",
  "telecommunications",
  "transformation",
  "unprecedented",
  "vulnerability",
  "wholeheartedly",
  "xylophone",
];

export type Difficulty = "easy" | "medium" | "hard";

function getWordBank(difficulty: Difficulty): string[] {
  switch (difficulty) {
    case "easy":
      return easyWords;
    case "medium":
      return [...easyWords, ...mediumWords];
    case "hard":
      return [...easyWords, ...mediumWords, ...hardWords];
    default:
      return easyWords;
  }
}

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function generateText(
  wordCount: number,
  difficulty: Difficulty = "medium",
): string {
  const wordBank = getWordBank(difficulty);
  const words: string[] = [];

  for (let i = 0; i < wordCount; i++) {
    const randomIndex = Math.floor(Math.random() * wordBank.length);
    words.push(wordBank[randomIndex]);
  }

  return words.join(" ");
}

export function generateParagraph(difficulty: Difficulty = "medium"): string {
  // Generate between 40-60 words for a good typing test
  const wordCount = Math.floor(Math.random() * 21) + 40;
  return generateText(wordCount, difficulty);
}
